### ISSUE TITLE
LagMonitor hint

### ISSUE THREAD

**Issue by xXSchrandXx** [vik1395/BungeeAuth-Minecraft#23]
Hey,

LagMonitor gives me a hint for your plugin:
`[Server thread/WARN]: [LagMonitor] Plugin BungeeAuth is performing a blocking action on the main thread. This could be a performance hit Socket: socket://localhost:3306. Such actions should be handled async from the main thread. Report it to the plugin author
[Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
java.lang.IllegalAccessException: null
	at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:55) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:42) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) [LagMonitor.jar:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) [?:1.8.0_144]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at sun.reflect.GeneratedConstructorAccessor141.newInstance(Unknown Source) [?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_144]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) [?:1.8.0_144]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) [?:1.8.0_144]
	at MySQL.openConnection(MySQL.java:34) [BungeeAuthValidator.jar:?]
	at Tables.checkPlayerEntry(Tables.java:13) [BungeeAuthValidator.jar:?]
	at Main.onjoin(Main.java:81) [BungeeAuthValidator.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by TuxCoding** [comment]
The source plugin is BungeeAuthValidator in this case.
